services:
  database:
    container_name: teztapauto_db
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: teztapauto_back
    build:
      context: .
    env_file:
      - .env
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - database
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --no-input &&
               gunicorn crm.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    container_name: teztapauto_nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media

volumes:
  postgres_data:
