services:
  database:
    container_name: teztapauto_db
    image: postgres
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: teztapauto_back
    build:
      context: .
    env_file:
      - .env
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - database
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --no-input &&
               gunicorn crm.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    container_name: teztapauto_nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media

  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/opt/redis/data

  celery:
    build: ./
    container_name: teztapauto_celery
    env_file:
      - /var/www/.env
    restart: always
    volumes:
      - ./:/app
      - /data/static:/app/static
      - /data/media:/app/media
    depends_on:
      - database
      - redis
    command: bash -c "celery -A teztapauto worker -B --loglevel=info"


volumes:
  postgres_data:
  redis-data:
