# Generated by Django 5.1.3 on 2024-12-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузова',
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order-images/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255, verbose_name='Модель')),
                ('car_year', models.CharField(max_length=4, verbose_name='Год автомобиля')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('second_phone', models.CharField(max_length=255, verbose_name='Второй номер телефона')),
                ('sample', models.ImageField(blank=True, null=True, upload_to='sample/', verbose_name='Образец')),
                ('vin_code', models.CharField(max_length=255, verbose_name='VIN код')),
                ('tech_passport', models.ImageField(blank=True, null=True, upload_to='tech_passport/', verbose_name='Тех. пасспорт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carbody', verbose_name='Кузов')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carmake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
