# Generated by Django 5.1.3 on 2024-12-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_car_body_alter_order_car_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='order',
            name='car_model',
        ),
        migrations.AddField(
            model_name='order',
            name='car_make_model',
            field=models.CharField(default='Неизвестно', max_length=255, verbose_name='Марка и модель'),
            preserve_default=False,
        ),
    ]
