# Generated by Django 5.1.3 on 2024-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_car_make_remove_order_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vin_image',
            field=models.ImageField(blank=True, null=True, upload_to='vin_code_images/', verbose_name='Фото VIN кода'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tech_passport',
            field=models.ImageField(blank=True, null=True, upload_to='tech_passport/', verbose_name='Тех. паспорт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vin_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VIN код'),
        ),
    ]
