# Generated by Django 5.1.3 on 2024-12-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_vin_image_alter_order_tech_passport_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.AlterField(
            model_name='orderprice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='orders.order'),
        ),
    ]
